# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20171025_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='confirmacion',
            field=models.BooleanField(default=False, verbose_name='Enfermedades del corazon'),
        ),
    ]
