# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellido(s)')),
                ('edad', models.IntegerField(null=True, verbose_name=b'Edad')),
                ('tipo_paciente', models.CharField(choices=[(b'Particular', b'Particular'), (b'Aseguranza', b'Aseguranza')], max_length=100, verbose_name='tipo paciente')),
                ('aseguranza', models.CharField(default=b'', max_length=100, null=True, verbose_name='aseguranza')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=100, null=True, unique=True, verbose_name='correo')),
                ('direccion', models.CharField(default=b'', max_length=200, null=True, verbose_name='Direccion')),
                ('comentarios', models.CharField(default=b'', max_length=500, null=True, verbose_name='Comentarios')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha_inicio')),
            ],
        ),
    ]
