# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, unique=True, verbose_name='nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellido(s)')),
                ('tipo_paciente', models.CharField(max_length=100, verbose_name='puesto')),
                ('telefono', models.CharField(max_length=100, null=True, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=100, null=True, unique=True, verbose_name='correo')),
                ('direccion', models.CharField(default=b'0', max_length=200, null=True, verbose_name='Direccion')),
                ('comentarios', models.CharField(default=b'0', max_length=500, null=True, verbose_name='Comentarios')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha_inicio')),
            ],
        ),
    ]
