# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(max_length=10, null=True, verbose_name=b'Edad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='nombre(s)'),
        ),
    ]
