# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='aseguranza',
            field=models.CharField(max_length=100, null=True, verbose_name='aseguranza'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_paciente',
            field=models.CharField(choices=[(b'Particular', b'Particular'), (b'Aseguranza', b'Aseguranza')], max_length=100, verbose_name='tipo paciente'),
        ),
    ]
