# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170608_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(null=True, verbose_name=b'Edad'),
        ),
    ]
