# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170529_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='aseguranza',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='aseguranza'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comentarios',
            field=models.CharField(default=b'', max_length=500, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default=b'', max_length=200, null=True, verbose_name='Direccion'),
        ),
    ]
