# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('empleados', '0002_auto_20170531_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True, verbose_name='fecha de visita')),
                ('motivo', models.CharField(default=b'', max_length=300, null=True, verbose_name='motivo')),
                ('precio', models.CharField(default=b'', max_length=50, null=True, verbose_name='Precio')),
                ('dolares', models.BooleanField(choices=[(b'Pesos', b'Pesos'), (b'Dolares', b'Dolares')], verbose_name='Divisa')),
                ('tipo_pago', models.CharField(choices=[(b'Efectivo', b'Efectivo'), (b'Tarjeta', b'Tarjeta'), (b'Cheque', b'Cheque')], max_length=50, null=True, verbose_name='tipo de pago')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
        ),
    ]
