# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fecha_visita',
            field=models.DateTimeField(verbose_name='fecha de visita'),
        ),
    ]
