# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_auto_20170601_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
