# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_auto_20170812_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fecha_visita',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
