# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_visitas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='dolares',
            field=models.CharField(choices=[(b'Pesos', b'Pesos'), (b'Dolares', b'Dolares')], max_length=50, null=True, verbose_name='Divisas'),
        ),
    ]
