# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_auto_20180117_0835'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0005_auto_20180118_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(default=b'', max_length=500, null=True, verbose_name='comentario')),
                ('fecha_receta', models.DateTimeField(verbose_name='Fecha')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
