# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='motivo',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='motivo'),
        ),
    ]
