# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='nombre(s)')),
                ('apellidos', models.CharField(max_length=200, verbose_name='apellido(s)')),
                ('puesto', models.CharField(max_length=100, verbose_name='puesto')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=100, null=True, verbose_name='correo')),
                ('direccion', models.CharField(default=b'0', max_length=200, verbose_name='Direccion')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha_inicio')),
            ],
        ),
    ]
