# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
    ]
