# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=200, null=True, verbose_name='Direccion'),
        ),
    ]
