# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20170126_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Empleado',
        ),
    ]
