# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20170808_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(null=True, verbose_name=b'Edad'),
        ),
    ]
