# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20170127_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='ModeloEmpleados',
        ),
    ]
