# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_auto_20170130_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeloEmpleados',
            new_name='Empleados',
        ),
    ]
