# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_auto_20170311_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default=b'0', max_length=200, verbose_name='Direccion'),
        ),
    ]
