# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleado_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='telefono'),
        ),
    ]
