# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10, null=True, verbose_name='sexo')),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='estado civil')),
                ('ocupacion', models.CharField(max_length=50, null=True, verbose_name='ocupacion')),
                ('alergias', models.BooleanField(default=False, verbose_name='Es alergico a alguna droga,anestesia,antibiotico?')),
                ('alergias_comentarios', models.CharField(default='', max_length=200, null=True, verbose_name='describa')),
                ('corazon', models.BooleanField(default=False, verbose_name='Enfermedades del corazon')),
                ('presion_arterial', models.BooleanField(default=False, verbose_name='Presion arterial')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('hepatitis', models.BooleanField(default=False, verbose_name='Hepatitis')),
                ('vih', models.BooleanField(default=False, verbose_name='Es usted portador del VIH')),
                ('embarazada', models.BooleanField(default=False, verbose_name='si es mujer, Esta usted embarazada')),
                ('medicamentos', models.BooleanField(default=False, verbose_name='Actualmente toma algun medicamento')),
                ('medicamentos_comentarios', models.CharField(default='', max_length=200, null=True, verbose_name='describa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
            options={
                'verbose_name': 'Historial de pacientes',
                'verbose_name_plural': 'Historial de pacientes',
            },
        ),
    ]
