# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='ocupacion',
            field=models.CharField(max_length=20, null=True, verbose_name='ocupacion'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='estado_civil',
            field=models.CharField(max_length=20, null=True, verbose_name='estado civil'),
        ),
    ]
