# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_auto_20170728_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='alergico',
            field=models.BooleanField(default=True),
        ),
    ]
