# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_historial_alergico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='alergico',
            field=models.BooleanField(default=False, verbose_name='Es alergico a alguna droga,anestesia,antibiotico'),
        ),
    ]
