# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_auto_20170728_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='arterial',
            field=models.BooleanField(default=False, verbose_name='Presion arterial'),
        ),
        migrations.AddField(
            model_name='historial',
            name='corazon',
            field=models.BooleanField(default=False, verbose_name='Enfermedades del corazon'),
        ),
        migrations.AddField(
            model_name='historial',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='historial',
            name='hemorragia',
            field=models.BooleanField(default=False, verbose_name='Ha tenido alguna hemorragia'),
        ),
        migrations.AddField(
            model_name='historial',
            name='hepatitis',
            field=models.BooleanField(default=False, verbose_name='Hepatitis'),
        ),
        migrations.AddField(
            model_name='historial',
            name='medicamento',
            field=models.BooleanField(default=False, verbose_name='Actualmente toma algun medicamento'),
        ),
        migrations.AddField(
            model_name='historial',
            name='mujer',
            field=models.BooleanField(default=False, verbose_name='si es mujer, Esta usted embarazada'),
        ),
        migrations.AddField(
            model_name='historial',
            name='vih',
            field=models.BooleanField(default=False, verbose_name='Es usted portador del VIH'),
        ),
    ]
