# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0005_auto_20170728_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='mujer',
            new_name='embarazada',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='medicamento',
            new_name='medicamentos',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='arterial',
            new_name='presion_arterial',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='alergico',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='hemorragia',
        ),
        migrations.AddField(
            model_name='historial',
            name='alergias',
            field=models.BooleanField(default=False, verbose_name='Es alergico a alguna droga,anestesia,antibiotico?'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='ocupacion',
            field=models.CharField(max_length=30, null=True, verbose_name='ocupacion'),
        ),
    ]
