# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0007_auto_20170728_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='alergias_comentarios',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='describa'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='medicamentos_comentarios',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='describa'),
        ),
    ]
