# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0008_auto_20170728_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name': 'Historial de pacientes', 'verbose_name_plural': 'Historial de pacientes'},
        ),
    ]
