# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(default=b'', max_length=300, null=True, verbose_name='motivo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('dolares', models.CharField(choices=[(b'Pesos', b'Pesos'), (b'Dolares', b'Dolares')], max_length=50, verbose_name='Divisa')),
                ('tipo_pago', models.CharField(choices=[(b'Efectivo', b'Efectivo'), (b'Tarjeta', b'Tarjeta'), (b'Cheque', b'Cheque'), (b'Transferencia bancaria', b'Transferencia bancaria'), (b'Pendiente', b'Pendiente')], max_length=50, null=True, verbose_name='tipo de pago')),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True, verbose_name='fecha de gasto')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
        ),
    ]
