# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateTimeField(verbose_name='fecha de gasto'),
        ),
    ]
